### PR TITLE
Add some more error types to the whitelist

### PR DESCRIPTION
**Pull request by ajohnstone**

### CODE REVIEW

**Review by AndersonZacharyT — APPROVED** [review]

**Comment by niftylettuce** [comment]
Please merge and version bump?

**Comment by niftylettuce** [comment]
I've released `@niftylettuce/is-retry-allowed` in the meanwhile until this is released.  Source available at https://github.com/niftylettuce/is-retry-allowed.

**Review by AndersonZacharyT — APPROVED** [review]

**Comment by sindresorhus** [comment]
I've taken over the maintenance of this package. New version is out: https://github.com/sindresorhus/is-retry-allowed/releases/tag/v1.2.0

**Comment by niftylettuce** [comment]
❤️ love as always @sindresorhus

**Comment by niftylettuce** [comment]
thank you 😄

**Pull request merged**
